--------------------------------------------------------
--  파일이 생성됨 - 화요일-3월-31-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CITY_COLLECT
--------------------------------------------------------

  CREATE TABLE JAVA2.CITY_COLLECT 
   (	CITY_COLLECT_ID NUMBER, 
	PRODUCT_ID VARCHAR2(30 BYTE), 
	CITY_ID NUMBER, 
	PAKAGE_ID VARCHAR2(50 BYTE), 
	CITY_NAME VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TS_STUDY ;
--------------------------------------------------------
--  Constraints for Table CITY_COLLECT
--------------------------------------------------------

  ALTER TABLE JAVA2.CITY_COLLECT MODIFY (PAKAGE_ID NOT NULL ENABLE);
  ALTER TABLE JAVA2.CITY_COLLECT MODIFY (PRODUCT_ID NOT NULL ENABLE);
  ALTER TABLE JAVA2.CITY_COLLECT MODIFY (CITY_COLLECT_ID NOT NULL ENABLE);

  COMMENT ON COLUMN CITY_COLLECT.CITY_COLLECT_ID IS '도시모음ID'
  COMMENT ON COLUMN CITY_COLLECT.PRODUCT_ID IS '여행상품ID'
  COMMENT ON COLUMN CITY_COLLECT.CITY_ID IS '도시ID'
  COMMENT ON COLUMN CITY_COLLECT.PAKAGE_ID IS '여행묶음ID'
  COMMENT ON COLUMN CITY_COLLECT.CITY_NAME IS '도시이름'
  COMMENT ON TABLE CITY_COLLECT  IS '도시모음 테이블'