--------------------------------------------------------
--  파일이 생성됨 - 화요일-3월-31-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_PACKAGE
--------------------------------------------------------

  CREATE TABLE JAVA2.T_PACKAGE 
   (	PACKAGE_ID VARCHAR2(50 BYTE), 
	PACKAGE_NAME VARCHAR2(200 BYTE), 
	PACKAGE_REGION VARCHAR2(30 BYTE), 
	PACKAGE_PRICE NUMBER, 
	PACKAGE_PIC VARCHAR2(200 BYTE), 
	PACKAGE_GRADE NUMBER, 
	PACKAGE_DEP_PERIOD1 VARCHAR2(40 BYTE), 
	TOTAL_PEOPLE NUMBER, 
	NOTICE VARCHAR2(3000 BYTE), 
	ADULT_PRICE NUMBER, 
	CHILD_PRICE NUMBER, 
	BABY_PRICE NUMBER, 
	ACCOUNT_BANK VARCHAR2(30 BYTE), 
	ACCOUNT VARCHAR2(30 BYTE), 
	PACKAGE_PERIOD VARCHAR2(30 BYTE), 
	AIR_START VARCHAR2(10 BYTE), 
	AIR_END VARCHAR2(10 BYTE), 
	PACKAGE_DEP_PERIOD2 VARCHAR2(40 BYTE), 
	VIEW_YN VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TS_STUDY ;
  
  COMMENT ON COLUMN T_PACKAGE.PACKAGE_ID IS '여행묶음ID'
  COMMENT ON COLUMN T_PACKAGE.PACKAGE_NAME IS '여행묶음명'
  COMMENT ON COLUMN T_PACKAGE.PACKAGE_REGION IS '지역'
  COMMENT ON COLUMN T_PACKAGE.PACKAGE_PRICE IS '금액'
  COMMENT ON COLUMN T_PACKAGE.PACKAGE_PIC IS '패키지사진'
  COMMENT ON COLUMN T_PACKAGE.PACKAGE_GRADE IS '평정'
  COMMENT ON COLUMN T_PACKAGE.PACKAGE_DEP_PERIOD1 IS '출발기간_처음'
  COMMENT ON COLUMN T_PACKAGE.TOTAL_PEOPLE IS '총인원'
  COMMENT ON COLUMN T_PACKAGE.NOTICE IS '전달사항'
  COMMENT ON COLUMN T_PACKAGE.ADULT_PRICE IS '성인요금'
  COMMENT ON COLUMN T_PACKAGE.CHILD_PRICE IS '아동요금'
  COMMENT ON COLUMN T_PACKAGE.BABY_PRICE IS '유아요금'
  COMMENT ON COLUMN T_PACKAGE.ACCOUNT_BANK IS '계좌은행'
  COMMENT ON COLUMN T_PACKAGE.ACCOUNT IS '계좌번호'
  COMMENT ON COLUMN T_PACKAGE.PACKAGE_PERIOD IS '여행기간'
  COMMENT ON COLUMN T_PACKAGE.AIR_START IS '출발_항공편'
  COMMENT ON COLUMN T_PACKAGE.AIR_END IS '도착_항공편'
  COMMENT ON COLUMN T_PACKAGE.PACKAGE_DEP_PERIOD2 IS '출발기간_마지막'
  COMMENT ON COLUMN T_PACKAGE.VIEW_YN IS '게시여부'
  COMMENT ON TABLE T_PACKAGE  IS '여행묶음 테이블'
  
  
  
--------------------------------------------------------
--  Constraints for Table T_PACKAGE
--------------------------------------------------------

  ALTER TABLE JAVA2.T_PACKAGE MODIFY (PACKAGE_ID NOT NULL ENABLE);
