--------------------------------------------------------
--  파일이 생성됨 - 화요일-3월-31-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_PRODUCT
--------------------------------------------------------

  CREATE TABLE JAVA2.T_PRODUCT 
   (	PRODUCT_ID VARCHAR2(100 BYTE), 
	PRODUCT_NAME VARCHAR2(200 BYTE), 
	START_DATE VARCHAR2(50 BYTE), 
	END_DATE VARCHAR2(50 BYTE), 
	RES_YN VARCHAR2(20 BYTE), 
	TOTAL_PEOPLE NUMBER, 
	APPLY_PEOPLE NUMBER, 
	NOTICE VARCHAR2(4000 BYTE), 
	ADULT_PRICE NUMBER, 
	CHILD_PRICE NUMBER, 
	BABY_PRICE NUMBER, 
	ACCOUNT VARCHAR2(50 BYTE), 
	ACCOUNT_BANK VARCHAR2(50 BYTE), 
	PACKAGE_PERIOD VARCHAR2(50 BYTE), 
	AIR_START VARCHAR2(20 BYTE), 
	AIR_END VARCHAR2(20 BYTE), 
	VIEW_YN VARCHAR2(20 BYTE), 
	AIR_LINE_NM VARCHAR2(100 BYTE), 
	PACKAGE_ID VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TS_STUDY ;
  
  COMMENT ON COLUMN T_PRODUCT.PRODUCT_ID IS '여행상품ID'
  COMMENT ON COLUMN T_PRODUCT.PRODUCT_NAME IS '여행상품이름'
  COMMENT ON COLUMN T_PRODUCT.START_DATE IS '출발일자'
  COMMENT ON COLUMN T_PRODUCT.END_DATE IS '도착일자'
  COMMENT ON COLUMN T_PRODUCT.RES_YN IS '예약가능'
  COMMENT ON COLUMN T_PRODUCT.TOTAL_PEOPLE IS '총인원'
  COMMENT ON COLUMN T_PRODUCT.APPLY_PEOPLE IS '신청인원'
  COMMENT ON COLUMN T_PRODUCT.NOTICE IS '전달사항'
  COMMENT ON COLUMN T_PRODUCT.ADULT_PRICE IS '성인요금'
  COMMENT ON COLUMN T_PRODUCT.CHILD_PRICE IS '아동요금'
  COMMENT ON COLUMN T_PRODUCT.BABY_PRICE IS '유아요금'
  COMMENT ON COLUMN T_PRODUCT.ACCOUNT IS '계좌번호'
  COMMENT ON COLUMN T_PRODUCT.ACCOUNT_BANK IS '계좌은행'
  COMMENT ON COLUMN T_PRODUCT.PACKAGE_PERIOD IS '여행기간'
  COMMENT ON COLUMN T_PRODUCT.AIR_START IS '출발_항공편'
  COMMENT ON COLUMN T_PRODUCT.AIR_END IS '도착_항공편'
  COMMENT ON COLUMN T_PRODUCT.VIEW_YN IS '게시여부'
  COMMENT ON COLUMN T_PRODUCT.AIR_LINE_NM IS '항공사명'
  COMMENT ON COLUMN T_PRODUCT.PACKAGE_ID IS '여행묶음ID'
  COMMENT ON TABLE T_PRODUCT  IS '여행상품 테이블'
--------------------------------------------------------
--  Constraints for Table T_PRODUCT
--------------------------------------------------------

  ALTER TABLE JAVA2.T_PRODUCT MODIFY (PRODUCT_ID NOT NULL ENABLE);
