--------------------------------------------------------
--  파일이 생성됨 - 화요일-3월-31-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CALENDAR
--------------------------------------------------------

  CREATE TABLE JAVA2.CALENDAR 
   (	CALENDAR_ID NUMBER, 
	SPOT_ID NUMBER, 
	DAY NUMBER, 
	CALENDAR_TITLE VARCHAR2(300 BYTE), 
	CALENDAR_CONTENT VARCHAR2(3000 BYTE), 
	PRODUCT_ID VARCHAR2(200 BYTE), 
	STEP NUMBER, 
	SPOT_PIC VARCHAR2(200 BYTE), 
	SPOT_NAME VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TS_STUDY ;

  COMMENT ON COLUMN CALENDAR.CALENDAR_ID IS '일정ID'
  COMMENT ON COLUMN CALENDAR.SPOT_ID IS '관광지ID'
  COMMENT ON COLUMN CALENDAR.DAY IS '일차'
  COMMENT ON COLUMN CALENDAR.CALENDAR_TITLE IS '일정제목'
  COMMENT ON COLUMN CALENDAR.CALENDAR_CONTENT IS '내용'
  COMMENT ON COLUMN CALENDAR.PRODUCT_ID IS '여행상품ID'
  COMMENT ON COLUMN CALENDAR.STEP IS '단계'
  COMMENT ON COLUMN CALENDAR.SPOT_PIC IS '관광지사진'
  COMMENT ON COLUMN CALENDAR.SPOT_NAME IS '관광지이름'
  COMMENT ON TABLE CALENDAR  IS '관광테마 테이블'
  